services:
  nutritionaladvice-microservice:
    image: zulenycr/nutritionaladvice-microservice:v9
    container_name: nutritionaladvice-microservice
    ports:
      - "5002:5000"  # Expone el puerto 5000 del contenedor en el puerto 5000 del host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db_service;Database=NutritionalAdvice;Username=nutritionaladvice_user;Password=11235813.zZ
      - RabbitMqSettings__Host=rabbitMQ
      - RabbitMqSettings__UserName=storeUser
      - RabbitMqSettings__Passwordt=storeUserPassword
      - RabbitMqSettings__VirtualHost=/
    depends_on:
      - db_service  # Asegura que MySQL se inicie antes que el microservicio
    networks:
      - nur-network
      - kong-net
  # Servicio para la base de datos MySQL
  db_service:
    image: zulenycr/nutritionaladvice-db:v2.1
    container_name: db_service
    environment:
      - POSTGRES_DB=NutritionalAdvice
      - POSTGRES_USER=nutritionaladvice_user
      - POSTGRES_PASSWORD=11235813.zZ
    ports:
      - "5440:5432"  # Expone el puerto 3306 del contenedor en el puerto 5432 del host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persiste los datos de la base de datos
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nutritionaladvice_user", "-d", "NutritionalAdvice"]
      interval: 10s
      retries: 5
      start_period: 20s
    networks:
      - nur-network

networks:
  nur-network:
    driver: bridge
  kong-net:
    external: true
# Volumen para persistir los datos de MySQL
volumes:
  postgres_data:
