# Use the base image mysql:latest
FROM mysql:8.0

# Set environment variables

ENV MYSQL_ROOT_PASSWORD=11235813.zZ
ENV MYSQL_DATABASE=NutritionalAdvice
ENV MYSQL_USER=nutritionaladvice_user
ENV MYSQL_PASSWORD=11235813.zZ

# Copy custom scripts or configuration files from your host to the container
COPY ./script-ini.sql /docker-entrypoint-initdb.d/