# Usa la imagen oficial de PostgreSQL 17.5
FROM postgres:17.5

# Variables de entorno (configuración inicial)
ENV POSTGRES_DB=NutritionalAdvice
ENV POSTGRES_USER=nutritionaladvice_user
ENV POSTGRES_PASSWORD=11235813.zZ

# Copia los scripts SQL de inicialización
COPY ./postgres-db-init.sql /docker-entrypoint-initdb.d/
